name: Code Coverage
on:
  push:
    branches:
      - master
jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Codecov
        uses: codecov/codecov-action@master


